### PR TITLE
Add scrolling through posts via volume keys. Closes #209

### LINKED ISSUE #209: Volume keys scrolling
A minor addition, scrolling through posts with the volume keys on a thread, could also be used while viewing images for next/previous

### PR DESCRIPTION
**Pull request by wadlieb**

### CODE REVIEW

**Comment by eugenkiss** [comment]
I like the effect very much! Good work :+1: 

Can I add an additional request? Namely, if you switch from portrait to landscape and then scroll via volume keys the distance is too great because it is still based on portrait. The fix is to recalculate `SCROLL_BY_HEIGHT` in the `postDelayed`-callback of `PostsActivity`s `onConfigurationChanged` method.

**Comment by eugenkiss** [comment]
Oh and another issue, if you have a `PostsDialog` open (i.e. you clicked on *Replies*) then the volume key scrolling scrolls the main thread behind but not the current `PostsDialog` at the top.

**Comment by wadlieb** [comment]
I will fix the `PostDialog` issue next :smiley:

**Comment by eugenkiss** [comment]
Good job!

**Pull request merged**
